# 1. Input
input {
  file {
    path => "/usr/share/logstash/logs/tomhoon-api-log.log"
    start_position => "beginning"
    stat_interval => 1
  }
}

# 2. Filter
filter {
}

# 3. Output
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "tomhoon-api-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}